export default {
  SET_ORDER_SUCCESS: 'SET_ORDER_SUCCESS',
  FETCH_ORDER_FAILURE: 'FETCH_ORDER_FAILURE',
  FETCH_ORDER_REQUEST: 'FETCH_ORDER_REQUEST',

  SET_FULFILLMENTS_SUCCESS: 'SET_FULFILLMENTS_SUCCESS',
  SET_FULFILLMENTS_ERROR: 'SET_FULFILLMENTS_ERROR',
  SET_BILLINGADDRESS_SUCCESS: 'SET_BILLINGADDRESS_SUCCESS',
  SET_FULFILLMENTS_SHIPPLACES_SUCCESS: 'SET_FULFILLMENTS_SHIPPLACES_SUCCESS',
  SET_CUSTOMER_SUCCESS: 'SET_CUSTOMER_SUCCESS',
  SET_PAYMENT_SUCCESS: 'SET_PAYMENT_SUCCESS',
  SET_PAYMENT_ERROR: 'SET_PAYMENT_ERROR',
  SET_TOTALS_SUCCESS: 'SET_TOTALS_SUCCESS',
  SET_TOTALS_ERROR: 'SET_TOTALS_ERROR',

  TOGGLE_SHIP: 'TOGGLE_SHIP',
};
